export const courses = [
  {
    name: "Data Structures & Algorithms",
    imageUrl: "https://placehold.co/300x150/E0F2F7/0284C7?text=DSA",
  },
  {
    name: "Frontend Development",
    imageUrl: "https://placehold.co/300x150/FFF3E0/F57C00?text=Frontend",
  },
  {
    name: "Backend Development",
    imageUrl: "https://placehold.co/300x150/E8F5E9/388E3C?text=Backend",
  },
  {
    name: "Database Fundamentals",
    imageUrl: "https://placehold.co/300x150/FCE4EC/C2185B?text=Database",
  },
  {
    name: "System Design",
    imageUrl: "https://placehold.co/300x150/E1F5FE/0277BD?text=System+Design",
  },
  {
    name: "Machine Learning Basics",
    imageUrl: "https://placehold.co/300x150/EDE7F6/5E35B1?text=ML",
  },
  {
    name: "Competitive Programming",
    imageUrl:
      "https://placehold.co/300x150/FFEBEE/D32F2F?text=Competitive+Programming",
  },
  {
    name: "Cloud Computing",
    imageUrl: "https://placehold.co/300x150/FFFDE7/FBC02D?text=Cloud",
  },
  {
    name: "Mobile Development (React Native)",
    imageUrl: "https://placehold.co/300x150/E3F2FD/1976D2?text=React+Native",
  },
  {
    name: "Cybersecurity Essentials",
    imageUrl: "https://placehold.co/300x150/F3E5F5/7B1FA2?text=Cybersecurity",
  },
];
export const problemCategories = [
  "All Problems",
  "Algorithms",
  "Data Structures",
  "Database",
  "Shell",
  "Concurrency",
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Searching",
  "Tree",
  "Graph",
  "Linked List",
  "Two Pointers",
  "Binary Search",
  "Backtracking",
  "Stack",
  "Queue",
  "Heap (Priority Queue)",
  "Recursion",
  "Bit Manipulation",
  "Divide and Conquer",
  "Trie",
  "Greedy",
  "Breadth-First Search",
  "Depth-First Search",
  "Union Find",
  "Segment Tree",
  "Binary Indexed Tree",
  "Topological Sort",
  "Design",
  "Geometry",
  "Random",
  "Sliding Window",
  "Brainteaser",
  "Memoization",
  "Game Theory",
  "Combinatorics",
  "Probability",
  "Reservoir Sampling",
  "Minimax",
];
